language: c

before_install:
  - wget https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export PATH=$PATH:$DEVKITARM/bin

install: 
  - sudo perl devkitARMupdate.pl
  
script:
  - make